.github/workflows/ci.yml
Makefile

This will publish artifacts to the sonatype snapshots repo on every PR build.

Publishing snapshots to sonatype in CI

---

.github/workflows/ci.yml

Only push snapshots on a PR

---

.github/scripts/setup-secrets.sh
.github/workflows/ci.yml
.github/workflows/release.yml
Makefile
client-python/.gitignore
client-python/setup.py

Setup pypi releases based on this article: https://realpython.com/pypi-publish-python-package/
Had to fiddle with versions since pypi and sonatype require different version formats.

Publish Python client snapshots to test pypi

---

core/src/main/scala/com/klibisz/elastiknn/api/ElasticsearchCodec.scala
core/src/main/scala/com/klibisz/elastiknn/api/package.scala
core/src/main/scala/com/klibisz/elastiknn/models/LshFunction.scala
es74x/src/main/scala/com/klibisz/elastiknn/mapper/VectorMapper.scala
es74x/src/main/scala/com/klibisz/elastiknn/query/KnnQueryBuilder.scala
es74x/src/main/scala/com/klibisz/elastiknn/query/LshFunctionCache.scala
testing/src/test/scala/com/klibisz/elastiknn/query/NearestNeighborsQuerySuite.scala

Only implemented in the scala client so far. Passes tests using randomly generated data.

Angular Lsh first pass

---

docs/pages/api.md

Fixes an error in the documentation discovered in alexklibisz#60.

Fix documentation for L2 LSH Query.

---

.github/workflows/benchmark.yaml
Makefile

Copied over from scratch repo.
You can only test this out on master hence the multiple PRs.

Benchmark workflow

---

.github/workflows/benchmark.yaml
testing/docker-compose.yml
testing/src/test/scala/com/klibisz/elastiknn/ClusterSpec.scala

Accounting for the resource constraints described here: https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners

Smaller cluster for testing

---

core/src/main/scala/com/klibisz/elastiknn/api/ElasticsearchCodec.scala
docs/pages/api.md
plugin/src/main/scala/com/klibisz/elastiknn/query/ExactQuery.scala
plugin/src/main/scala/com/klibisz/elastiknn/query/KnnQueryBuilder.scala
testing/src/test/scala/com/klibisz/elastiknn/query/NearestNeighborsQuerySpec.scala

Re: #97 
This seems to already work when using a bool query. Just added a test and added docs. 
I couldn't reproduce the index out of bounds exceptions mentioned by a couple users who were trying something similar to this.

Pre filter query

---

LICENSE.txt
build.gradle
readme.md

This seems to be the more common license among Elasticsearch-related projects.

Switch back to apache license

---

changelog.md
elastiknn-api4s/src/main/scala/com/klibisz/elastiknn/package.scala
elastiknn-lucene/src/main/java/org/apache/lucene/search/MatchHashesAndScoreQuery.java
elastiknn-plugin/src/main/scala/com/klibisz/elastiknn/ElastiknnException.scala
elastiknn-plugin/src/main/scala/com/klibisz/elastiknn/mapper/VectorMapper.scala
elastiknn-plugin/src/main/scala/com/klibisz/elastiknn/query/ExactQuery.scala
elastiknn-plugin/src/main/scala/com/klibisz/elastiknn/query/KnnQueryBuilder.scala
elastiknn-plugin/src/main/scala/com/klibisz/elastiknn/query/SparseIndexedQuery.scala
elastiknn-plugin/src/main/scala/com/klibisz/elastiknn/utils/CirceUtils.scala
elastiknn-testing/src/main/scala/com/klibisz/elastiknn/testing/ElasticAsyncClient.scala
elastiknn-testing/src/test/scala/com/klibisz/elastiknn/query/NearestNeighborsQuerySpec.scala

Ensure DocIdSetIterator starts iterating at -1. Rename all exceptions to ElastiknnFooException.

---

build.gradle
changelog.md
docs/pages/api.md
elastiknn-lucene/src/main/java/org/apache/lucene/search/MatchHashesAndScoreQuery.java
elastiknn-testing/src/test/scala/com/klibisz/elastiknn/query/NearestNeighborsQuerySpec.scala

This came up in #182 
See my comment: https://github.com/alexklibisz/elastiknn/issues/182#issuecomment-717991764

Log warning when approx query finds fewer matches than the given number of candidates

---

.github/workflows/ci.yml
.github/workflows/release.yml

Based on: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

Maybe fix release workflow

---

elastiknn-testing/src/test/scala/com/klibisz/elastiknn/query/ApproximateQueryTotalHitsSuite.scala
elastiknn-testing/src/test/scala/com/klibisz/elastiknn/query/MixedIndexSearchDeleteSuite.scala

Re #240 . Unable to replicate the problematic behavior. At least good to have a test suite that covers it.

Test to ensure the same query returns the same results when repeated

---

readme.md

Finally got around to finishing up moving my side project to use Elastiknn.  
Thanks for your help and fixing the few bugs I reported :)

Add rep0st as a user of Elastiknn

---

client-python/elastiknn/api.py
client-python/elastiknn/models.py
client-python/elastiknn/utils.py
docs/pages/index.md

Renaming Angular to Cosine in Python client

---

elastiknn-client-java/src/main/java/com/klibisz/elastiknn/ElastiknnNearestNeighborsQueryBuilder.java
elastiknn-client-java/src/main/java/com/klibisz/elastiknn/api4j/ElastiknnNearestNeighborsQuery.java
elastiknn-client-java/src/main/java/com/klibisz/elastiknn/api4j/Similarity.java
elastiknn-models/src/main/java/com/klibisz/elastiknn/models/ExactModel.java
elastiknn-plugin/src/main/scala/com/klibisz/elastiknn/models/Cache.scala
elastiknn-plugin/src/main/scala/com/klibisz/elastiknn/models/ExactSimilarityFunction.scala
elastiknn-testing/src/test/scala/com/klibisz/elastiknn/query/JavaClientSuite.scala
elastiknn-testing/src/test/scala/com/klibisz/elastiknn/query/RecallSuite.scala

Re #277 
Same as #293 and #294, but for Java client.

Renaming Angular to Cosine in Java client

---

docs/pages/api.md
docs/pages/installation.md

Re #277 
Version bump and some cleanup in the docs.

Bump version to release "Angular" to "Cosine" rename

---

build.gradle
developer-guide.md
elastiknn-api4s/src/main/scala/com/klibisz/elastiknn/api/package.scala
elastiknn-benchmarks/src/main/scala/com/klibisz/elastiknn/benchmarks/DatasetClient.scala
elastiknn-benchmarks/src/main/scala/com/klibisz/elastiknn/benchmarks/ResultClient.scala
elastiknn-benchmarks/src/main/scala/com/klibisz/elastiknn/benchmarks/SearchClient.scala
elastiknn-client-elastic4s/src/main/scala/com/klibisz/elastiknn/client/ElastiknnClient.scala
elastiknn-client-elastic4s/src/main/scala/com/klibisz/elastiknn/client/ElastiknnRequests.scala
elastiknn-plugin/src/main/scala/com/klibisz/elastiknn/utils/CirceUtils.scala
elastiknn-testing/src/main/scala/com/klibisz/elastiknn/testing/ExactSimilarityReference.scala
elastiknn-testing/src/main/scala/com/klibisz/elastiknn/testing/SilentMatchers.scala
elastiknn-testing/src/test/scala/com/klibisz/elastiknn/api/ElasticsearchCodecSuite.scala
elastiknn-testing/src/test/scala/com/klibisz/elastiknn/mapper/VectorMapperSuite.scala
elastiknn-testing/src/test/scala/com/klibisz/elastiknn/utils/CirceUtilsSuite.scala

As per discussion in https://github.com/alexklibisz/elastiknn/issues/316#issuecomment-956039127

Scala 2.13

---

README.md
elastiknn-benchmarks/README.md
examples/ann-benchmarks/README.md

- #383
Fixes the READMEs that were mixed up in #384.
Better proof reading

#383: Fix the READMEs

---

README.md

Link the related issues as a markdown list.
- #383
Fix one last typo and move developer-guide note to new contributing section.
Proof reading

#383: Fix typo, add contributing section

---

.gitmodules

- #387 
Bumped to latest upstream ann-benchmarks commit.
CI

#387: Bump to latest ann-benchmarks

---

.github/workflows/ci.yml
.github/workflows/release.yml
elastiknn-testing/docker-compose.yml
taskfiles/Taskfile.cluster.yaml

None
Changes needed to rename master to main.
Standard CI

Build: Rename main branch to main

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/scripts/delete-snapshot-releases.sh
elastiknn-testing/docker-compose.yml

None
Fix a couple more references to "master"
Standard CI

Build: fix a couple more references to "master"

---

.github/scripts/delete-snapshot-releases.sh
.github/workflows/release.yml
taskfiles/Taskfile.jvm.yaml

None
Put back the setup-java step in the release.yml. It was erroneously deleted in https://github.com/alexklibisz/elastiknn/commit/93550ce6e5da37dc470d004403f830f987cb3f09
Will run a release, see what happens

Build: fix release.yml

---

taskfiles/Taskfile.jvm.yaml

None
Finish converting the hub command to a task command.
Will test in the release workfow

Build: fix plugin:publish:release task

---

.github/workflows/release.yml
taskfiles/Taskfile.docs.yaml

- #442 
Implemented a job in release.yaml to upload static HTML (generated by Jekyll) to Github pages.
Will run after merging

Build: publish site to Github pages

---

.github/scripts/setup-env.sh
.github/workflows/ci.yml
.github/workflows/release.yml
Taskfile.yaml
taskfiles/Taskfile.docs.yaml

- #442
- Removed rsync steps and related build setup from the old site
Merge-and-check

Build: Remove release steps for old site

---

docs/pages/installation.md
docs/pages/libraries.md

#391 
Documenting the elasticsearch-7x branch, on the main branch.
Standard CI

Docs: document the elasticsearch 7.x branch and releases

---

.github/workflows/release.yml
docs/pages/installation.md
docs/pages/libraries.md

#391 
- Merge the main branch into the elasticsearch-7x branch
Standard CI

Build: merge main into elasticsearch-7x

---

docs/pages/installation.md

#391 
- Just remove a stale line in installation.md
Standard CI

Docs: fix versions table on installation.md

---

.github/workflows/release.yml
docs/pages/installation.md
docs/pages/libraries.md

#391 
Same as #467, but this time I won't squash+merge, I'll just merge the commits.
Standard CI

Build: merge main into elasticsearch-7x (again)

---

.github/workflows/release.yml
docs/pages/installation.md
docs/pages/libraries.md

#391 
Trying same as #469, but this time with a merge commit. Mainly trying to get rid of the misleading "n commits behind" that still shows up even after I rebased on those commits.
Standard CI

Build: merge main into elasticsearch-7x (again, again)

---

.github/workflows/release.yml

#391 
Merge main into elasticsearch-7x
Standard CI

Build: fix quotes from previous commit

---

Taskfile.yaml

Same as #475, but for elasticsearch-7x branch.

Build: fix the target commit when releasing

---

.github/workflows/scala-steward.yaml

None
Added a scala-steward workflow based on https://github.com/scala-steward-org/scala-steward-action
No tests before merging

Build: add scala-steward workflow

---

elastiknn-models-benchmarks/src/main/scala/com/klibisz/elastiknn/vectors/VectorOpsJmhBenchmark.scala
elastiknn-models/src/main/java/com/klibisz/elastiknn/vectors/DefaultFloatVectorOps.java
elastiknn-models/src/main/java/com/klibisz/elastiknn/vectors/FloatVectorOps.java
elastiknn-models/src/main/java/com/klibisz/elastiknn/vectors/PanamaFloatVectorOps.java

#495 
Cleaning up some internals. No behavior/functionality changes.
Standard CI

Some internal cleanup from previous PR

---

.github/scripts/delete-snapshot-releases.sh
.github/workflows/ci.yaml
.github/workflows/ci.yml
.github/workflows/cleanup-snapshots.yaml
.github/workflows/release.yml
elastiknn-plugin/src/it/scala/com/klibisz/elastiknn/RecallSuite.scala

None
* Removed SBT caching (not worth the complexity)
* Removed some cases from RecallSuite, which should speed up testing
* Fixed the release cleanup script
* Added timeouts to all steps to quickly catch hanging builds
How was it validated?

Various CI improvements

---

README.md
docs/_config.yml
docs/_posts/multimodal-search-raw.html
examples/tutorial-notebooks/multimodal-search-amazon-products.ipynb

Moving the docs to https://alexklibisz.github.io/elastiknn

Docs: change URL to https://alexklibisz.github.io/elastiknn

---

.github/workflows/release.yml

Build: fix python version for docs release job

---

README.md

We can just click the Actions tab

Docs: remove builds section from readme

---

docs/_posts/2021-07-30-how-does-elastiknn-work.md

N/A
Missed one in #590 
Merge, release, check

Docs: fix another image URL

---

Taskfile.yaml

None
Setting ES_JAVA_OPTS to a reasonable value for jvmRunLocal and jvmRunLocalDebug

Build: set ES_JAVA_OPTS for jvmRunLocal and jvmRunLocalDebug

---

.github/workflows/release-docs.yml

None
See title
Will test after merging

Build: fix name in release-docs workflow

---

.github/workflows/release-docs.yml

None
See title
Test after merging

Build: remove dependency from release-docs workflow

---

.github/workflows/ci.yaml
.github/workflows/delete-old-pre-releases.yaml
.github/workflows/release-docs.yml
.github/workflows/release.yml

None
Bumping composite actions to see if it fixes some recurring issues:
Maybe it's a coincidence but this actually seems to work first-try:
CI

Build: bump composite actions

---

Taskfile.yaml
ann-benchmarks/config.yml

#611 
This makes it easier to iterate on the parameters.
CI and tested locally

Performance: keep a local copy of the ann-benchmarks config.yml file
