- testing/build.gradle
- testing/src/test/scala/com/klibisz/elastiknn/query/NearestNeighborsQuerySuite.scala
The random names were repeating more often than you'd like for something random.
> [testing] removed fancy random index names in favor of simpler UUIDs

- client-python/elastiknn/api.py
- docs/pages/python-client.md
- docs/pages/scala-client.md
Issue #67 reminded me that I hadn't written dataclasses for all of the mappings and queries.
This PR adds those dataclasses as well as a more complete python-client page in the docs.
> Expand and document python client

- benchmarks/src/main/scala/com/klibisz/elastiknn/benchmarks/Execute.scala
- plugin/src/main/scala/com/klibisz/elastiknn/mapper/VectorMapper.scala
- plugin/src/main/scala/com/klibisz/elastiknn/query/LshQuery.scala
- plugin/src/main/scala/com/klibisz/elastiknn/query/SparseIndexedQuery.scala
More about norms here: https://www.elastic.co/guide/en/elasticsearch/reference/current/norms.html
I setup a benchmark for the SparseIndexed mapping/query and noticed a lot of time spent in the Lucene80NormsProducer class. 
Setting `.omitNorms(true)` in a few places seems to get rid of that class in the sampler. It decreases the time for the `ExecuteLocal` benchmark from 100 seconds for 1000 serial queries to ~85 seconds for 1000 serial queries and 74 seconds to 62 seconds for parallel queries. I also noticed they used the same setting here: https://github.com/elastic/elasticsearch/pull/44374/files#diff-3e8da1369743959b46f7e6fa0d63c1afR56
I checked to see if it makes a difference with AngularLSH but didn't see a meaningful speedup. I didn't see the NormsProducer class in the sampler in …
> Disable norms on fields used to store LSH hashes

- benchmarks/src/main/scala/com/klibisz/elastiknn/benchmarks/Execute.scala
- changelog.md
- plugin/src/main/scala/com/klibisz/elastiknn/query/LshQuery.scala
- plugin/src/main/scala/com/klibisz/elastiknn/query/SparseIndexedQuery.scala
Another modest improvement to SparseIndexedQuery and LshQuery.
> Use ConstantScoreQuery to wrap TermQueries for SparseIndexedQuery and LshQuery

- benchmarks/src/main/scala/com/klibisz/elastiknn/benchmarks/package.scala
- changelog.md
- client-python/elastiknn/api.py
- core/src/main/java/com/klibisz/elastiknn/storage/UnsafeSerialization.java
- core/src/main/scala/com/klibisz/elastiknn/api/package.scala
- core/src/main/scala/com/klibisz/elastiknn/models/LshFunction.scala
- core/src/main/scala/com/klibisz/elastiknn/storage/BitBuffer.scala
- docs/pages/api.md
- examples/demo/webapp/app/models/Dataset.scala
- plugin/src/main/scala/com/klibisz/elastiknn/query/LshQuery.scala
- testing/src/test/scala/com/klibisz/elastiknn/api/ElasticsearchCodecSuite.scala
- testing/src/test/scala/com/klibisz/elastiknn/query/NearestNeighborsQueryRecallSuite.scala
- testing/src/test/scala/com/klibisz/elastiknn/storage/BitBufferSuite.scala
Re #96 
Parameter names are now based on the conventions in the [LSH wikipedia article](https://en.wikipedia.org/wiki/Locality-sensitive_hashing#LSH_algorithm_for_nearest_neighbor_search) and material from Indyk, et. al, e.g. [these slides](http://people.csail.mit.edu/indyk/mmds.pdf).
Also improved some internal conventions, e.g. using BitBuffer to abstract bit operations.
> Revise LSH parameter names

- changelog.md
- elastiknn-lucene/src/main/java/org/apache/lucene/search/KthGreatest.java
- elastiknn-lucene/src/main/java/org/apache/lucene/search/MatchHashesAndScoreQuery.java
- elastiknn-testing/src/test/scala/com/klibisz/elastiknn/query/MatchHashesAndScoreQuerySuite.scala
- elastiknn-testing/src/test/scala/com/klibisz/elastiknn/query/NearestNeighborsQueryRecallSuite.scala
- elastiknn-testing/src/test/scala/com/klibisz/elastiknn/search/KthGreatestSuite.scala
In the previous implementation, if there were multiple docs with matching hash counts = the kth greatest matching hash count, all of them would be emitted.
For example, if matching hash counts were `1,2,2,2,2,2,3,4`, and `candidates = 3`, it would emit the docs corresponding to any count >= 2. 
Now it will only emit the docs with count > 2 and one of the docs with count = 2.
Also removes some unnecessary repetition from the recall suite.
> Limit number of doc ids emitted from MatchHashesAndScoreQuery

- changelog.md
- client-python/elastiknn/client.py
- client-python/elastiknn/models.py
- examples/ann-benchmarks/readme.md
- examples/ann-benchmarks/slurp-logs.sh
This uses iterators (iterables ?) to produce the elastiknn vectors lazily instead of keeping them all in memory.
Seems to fix some memory issues I was having with the ann-benchmarks project, where the containers would spike over 10GB of memory and crash.
> More memory efficient implementation of ElastiknnModel in python client

- changelog.md
- elastiknn-lucene/src/main/java/com/klibisz/elastiknn/lucene/ArrayHitCounter.java
- elastiknn-lucene/src/main/java/org/apache/lucene/search/KthGreatest.java
- elastiknn-lucene/src/main/java/org/apache/lucene/search/MatchHashesAndScoreQuery.java
- elastiknn-testing/src/test/scala/com/klibisz/elastiknn/query/MatchHashesAndScoreQuerySuite.scala
- elastiknn-testing/src/test/scala/com/klibisz/elastiknn/query/NearestNeighborsQuerySpec.scala
Based on #158 
So far it seems that the solution is:
1. Explicitly handle the possibility of `null` returned when calling `leafReader.terms(field)`.
2. Use `leafReader.numDocs` instead of `indexReader.numDocs` to determine the total number of possible docs.
Added a test for this scenario: index some docs, run a search, delete one doc, run a search, put the doc back, run a search. This passes locally.
> Fix NPE when searching after deleting docs

- elastiknn-testing/src/test/scala/com/klibisz/elastiknn/query/MatchHashesAndScoreQueryPerformanceSuite.scala
It obfuscates the issues noted in #160
> Stop using in-memory codec in performance suite

- elastiknn-lucene/src/main/java/org/apache/lucene/search/MatchHashesAndScoreQuery.java
- elastiknn-testing/src/test/scala/com/klibisz/elastiknn/query/NearestNeighborsQuerySpec.scala
Related to #158 
Make the hit counter allocate `reader.maxDocs` instead of `reader.numDocs`, because `reader.numDocs` gets decreased when docs get deleted, even though the largest docId will still be the same.
Also made the testing a bit more robust.
> Fix incorrect counter configuration that was causing array out of bounds errors

- changelog.md
- docs/pages/api.md
- elastiknn-testing/src/test/scala/com/klibisz/elastiknn/query/NearestNeighborsQuerySpec.scala
The original suggestion to use a bool query results in evaluating all docs. 
The correct way to do it is to use a standard query with a rescorer.
> Use a query rescorer to run KNN on filtered docs

- elastiknn-lucene/src/main/java/com/klibisz/elastiknn/search/ArrayHitCounter.java
- elastiknn-lucene/src/main/java/com/klibisz/elastiknn/search/HitCounter.java
- elastiknn-lucene/src/main/java/org/apache/lucene/search/MatchHashesAndScoreQuery.java
- elastiknn-testing/src/test/scala/com/klibisz/elastiknn/query/NearestNeighborsQuerySpec.scala
- HitCounter tracks the range of docIds which have hits (i.e. the min docId with hits and the max).
- DocIdSetIterator only iterates over this range. Previously iterated over all docIds.
- Had to slightly tweak the "deleting vectors" test. It's tricky to explain, but because the test had a mapping with a high value for `k`, the original query had a min candidate count of 0. After deleting some docs and re-inserting them to a new segment, four of the docs that were returned for the original query were no longer being returned because they still had a count of zero, but this time there was only one other non-zero doc in the segment, so those four docs were not being accessed.
> Simplifying some query internals

- elastiknn-testing/src/test/scala/com/klibisz/elastiknn/query/NearestNeighborsQueryRecallSuite.scala
This is a more correct way to compute recall. Basically, recall is the proportion of documents with scores >= the minimum exhaustive score.
> Use lowest correct score to compute recall in NearestNeighborsQueryRecallSuite

- .esopts
- changelog.md
- client-python/elastiknn/client.py
- client-python/elastiknn/models.py
- elastiknn-benchmarks/src/main/scala/com/klibisz/elastiknn/benchmarks/LocalBenchmark.scala
- elastiknn-benchmarks/src/main/scala/com/klibisz/elastiknn/benchmarks/SearchClient.scala
- Removed threadpool from python `ElastiknnModel`. There's a non-trivial cost to using this, and the benchmarking code that uses this client is already single-threaded by design.
- Added method `set_query_params` to python `ElastiknnModel`. This lets you update the query parameters once instead of doing it on every call to the `kneighbors` method.
- Using `filter_path` parameter in python `es.search()` method calls. This seems to add about 10 queries/sec. I guess there's some non-negligible cost to how the Elasticsearch python library parses JSON responses?
- Switched to using the recorded time instead of the Elasticsearch response `took` time in Scala benchmarks.
> Some tweaks to benchmarks and python client for faster benchmarking

- changelog.md
- docs/pages/api.md
- elastiknn-api4s/src/main/scala/com/klibisz/elastiknn/api/ElasticsearchCodec.scala
- elastiknn-plugin/src/main/scala/com/klibisz/elastiknn/mapper/VectorMapper.scala
- elastiknn-plugin/src/main/scala/com/klibisz/elastiknn/utils/CirceUtils.scala
- elastiknn-testing/src/test/scala/com/klibisz/elastiknn/api/ElasticsearchCodecSuite.scala
- elastiknn-testing/src/test/scala/com/klibisz/elastiknn/mapper/VectorMapperSuite.scala
Based on #177 
Introduces a shorthand alternative format for dense and sparse vectors that makes it easier to work with ES-connectors that don't allow nested docs.
Dense vectors can be represented as a simple array:
`{ "vec": [0.1, 0.2, 0.3, ...] }` is equivalent to `{ "vec": { "values": [0.1, 0.2, 0.3] }}`.
`{"vec": [[1, 3, 5, ...], 100] }` is equivalent to `{ "vec": { "true_indices": [1,3,5,...], "total_indices": 100 }}`
The main trick in getting this to work was figuring out I had to make the `FieldMapper` extend the `ArrayValueMapperParser` in order for Elasticsearch to let me parse a Json Array.
> Shorthand JSON format for vectors

- .esopts
- changelog.md
- elastiknn-plugin/src/main/scala/com/klibisz/elastiknn/ElastiknnPlugin.scala
- elastiknn-plugin/src/main/scala/com/klibisz/elastiknn/query/ExactQuery.scala
- elastiknn-plugin/src/main/scala/com/klibisz/elastiknn/query/HashingQuery.scala
- elastiknn-plugin/src/main/scala/com/klibisz/elastiknn/query/KnnQueryBuilder.scala
- elastiknn-plugin/src/main/scala/com/klibisz/elastiknn/storage/StoredVec.scala
- elastiknn-plugin/src/main/scala/com/klibisz/elastiknn/storage/VectorCache.scala
- elastiknn-testing/src/test/scala/com/klibisz/elastiknn/models/PermutationLshModelSuite.scala
- elastiknn-testing/src/test/scala/com/klibisz/elastiknn/query/MatchHashesAndScoreQueryPerformanceSuite.scala
Adds a global guava cache for dense vectors and another for sparse vectors.
The main motivation for this is that versions above 7.6.2 use a version of Lucene that introduced higher compression to binary doc values fields. 
So it takes significantly longer to consume the vectors from Lucene to do exact similarity scoring.
The caches are instantiated in the `Elastiknn#getPlugin` method and get woven through the various query-related classes.
Caching is configurable using the parameters below, shown with their default values:
```
elastiknn.cache.enabled=false           # whether to use caching
elastiknn.cache.capacity_mb=512     # capacity limit of each cache in megabytes
elastiknn.cache.ttl_seconds=600       # TTL (expire-after-write) for any entry in each cache
```
> Vector caching (optimization intended mainly for 7.9.2 upgrade)

- changelog.md
- docs/pages/api.md
- elastiknn-plugin/src/main/scala/com/klibisz/elastiknn/ElastiknnPlugin.scala
- elastiknn-plugin/src/main/scala/com/klibisz/elastiknn/query/ExactQuery.scala
- elastiknn-plugin/src/main/scala/com/klibisz/elastiknn/query/KnnQueryBuilder.scala
- elastiknn-plugin/src/main/scala/com/klibisz/elastiknn/query/KnnScoreFunctionBuilder.scala
- elastiknn-testing/src/test/scala/com/klibisz/elastiknn/query/NearestNeighborsQuerySpec.scala
This enables using elastiknn in function score queries:
```
{
"size": 3,
"query": {
"function_score": {
"query": {
"term": {
"color": "blue"
}
},
"elastiknn_nearest_neighbors": {
"field": "vec",
"similarity": "angular",
"model": "exact",
"vec": {
"values": [
0.1,
0.2,
0.3
]
}
}
}
}
}
```
> elastiknn_nearest_neighbors score function

- Makefile
- build.gradle
- changelog.md
- elastiknn-benchmarks/src/main/scala/com/klibisz/elastiknn/benchmarks/Aggregate.scala
- elastiknn-benchmarks/src/main/scala/com/klibisz/elastiknn/benchmarks/LocalBenchmark.scala
- elastiknn-plugin/Dockerfile
Also removes some benchmarking cruft.
Benchmarking results look solid: 13.14 q/s for exact fashion-mnist, 222.22 q/s for L2 LSH.
> Bump ES from 7.9.2 to 7.9.3

- .scalafmt.conf
- build.gradle
- elastiknn-client-elastic4s/src/main/scala/com/klibisz/elastiknn/client/ElastiknnClient.scala
- elastiknn-plugin/src/main/scala/com/klibisz/elastiknn/query/KnnScoreFunctionBuilder.scala
- elastiknn-testing/src/test/scala/com/klibisz/elastiknn/query/DocsWithMissingVectorsSuite.scala
- elastiknn-testing/src/test/scala/com/klibisz/elastiknn/query/FunctionScoreQuerySuite.scala
- elastiknn-testing/src/test/scala/com/klibisz/elastiknn/query/MixedIndexSearchDeleteSuite.scala
- elastiknn-testing/src/test/scala/com/klibisz/elastiknn/query/QueryRescorerSuite.scala
- elastiknn-testing/src/test/scala/com/klibisz/elastiknn/query/RecallSuite.scala
- Function score queries cannot support queries with stored vectors.
There's no place where we could make an async call to fetch the stored vector.
Added an error message that communicates this more explicitly.
- Added a test for the new error message.
- Minor change in client error handling: don't wrap an exception in a StrictFailureException.
- Started using Futil for async control in some of the tests.
- Scalafmted a few files.
> Better error for function score query with stored vector.

- .github/scripts/latestchanges.py
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Taskfile.jvm.yml
Instead of maintaining commits _and_ a changelog, just use the commits.
> Use git commits instead of changelog.md in release

- docs/pages/api.md
- elastiknn-api4s/src/main/scala/com/klibisz/elastiknn/api/ElasticsearchCodec.scala
- elastiknn-api4s/src/main/scala/com/klibisz/elastiknn/api/package.scala
- elastiknn-benchmarks/src/main/scala/com/klibisz/elastiknn/benchmarks/Execute.scala
- elastiknn-benchmarks/src/main/scala/com/klibisz/elastiknn/benchmarks/Generate.scala
- elastiknn-benchmarks/src/main/scala/com/klibisz/elastiknn/benchmarks/package.scala
- elastiknn-models/src/main/java/com/klibisz/elastiknn/models/CosineLshModel.java
- elastiknn-plugin/src/main/scala/com/klibisz/elastiknn/mapper/VectorMapper.scala
- elastiknn-plugin/src/main/scala/com/klibisz/elastiknn/models/Cache.scala
- elastiknn-plugin/src/main/scala/com/klibisz/elastiknn/models/ExactSimilarityFunction.scala
- elastiknn-plugin/src/main/scala/com/klibisz/elastiknn/query/ElastiknnQuery.scala
- elastiknn-testing/src/main/scala/com/klibisz/elastiknn/testing/ExactSimilarityReference.scala
- elastiknn-testing/src/main/scala/com/klibisz/elastiknn/testing/TestData.scala
- elastiknn-testing/src/test/scala/com/klibisz/elastiknn/api/ElasticsearchCodecSuite.scala
- elastiknn-testing/src/test/scala/com/klibisz/elastiknn/models/CosineLshModelSuite.scala
- elastiknn-testing/src/test/scala/com/klibisz/elastiknn/models/ExactSimilarityFunctionSuite.scala
- elastiknn-testing/src/test/scala/com/klibisz/elastiknn/models/PermutationLshModelSuite.scala
- elastiknn-testing/src/test/scala/com/klibisz/elastiknn/query/ApproximateQueryTotalHitsSuite.scala
- elastiknn-testing/src/test/scala/com/klibisz/elastiknn/query/DocsWithMissingVectorsSuite.scala
- elastiknn-testing/src/test/scala/com/klibisz/elastiknn/query/DocsWithMultipleVectorsSuite.scala
- elastiknn-testing/src/test/scala/com/klibisz/elastiknn/query/FunctionScoreQuerySuite.scala
- elastiknn-testing/src/test/scala/com/klibisz/elastiknn/query/JavaClientSuite.scala
- elastiknn-testing/src/test/scala/com/klibisz/elastiknn/query/QueryRescorerSuite.scala
- elastiknn-testing/src/test/scala/com/klibisz/elastiknn/query/RecallSuite.scala
This PR renames all instanes of "Angular" to "Cosine" in the plugin and scala client. 
See discussion on #277 for justification.
The serialization layer maintains backwards compatibility, so that any reference of Angular is mapped to Cosine.
There will be follow-ups to update the Python and Java clients as well.
> Renaming "Angular" to "Cosine" in Plugin and Scala client (Re #277)

- elastiknn-testing/src/test/scala/com/klibisz/elastiknn/query/FunctionScoreQuerySuite.scala
Adds an integration test that reproduces the issue. Unfortunately, so far I've found no way to resolve the issue. It seems that Elasticsearch non-deterministically evaluates the function on the first <size> docs that match the term query.
> Issue #298: Integration test to reproduce the issue

- elastiknn-testing/src/test/scala/com/klibisz/elastiknn/query/ApproximateQueryTotalHitsSuite.scala
- elastiknn-testing/src/test/scala/com/klibisz/elastiknn/query/MixedIndexSearchDeleteSuite.scala
A couple of the tests were creating indexes w/ > 1 replica.
Since there is only one data node, this made cluster status "yellow".
This only came up in #317, possibly due to changed scalatest ordering.
Re: #316
> Tests: Set test index replication to 1

- .github/workflows/ci.yml
- elastiknn-testing/docker-compose.yml
This will entirely skip the "publish-snapshots" job when another user makes a PR. This currently fails bc Github (correctly) prevents sharing credentials across accounts.
> Build: only publish snapshots if actor is alexklibisz and tests have passed

- elastiknn-testing/src/test/scala/com/klibisz/elastiknn/ClusterSpec.scala
- elastiknn-testing/src/test/scala/com/klibisz/elastiknn/query/ApproximateQueryTotalHitsSuite.scala
- elastiknn-testing/src/test/scala/com/klibisz/elastiknn/query/MixedIndexSearchDeleteSuite.scala
For some reason the cluster ends up in "yellow" in GH actions, but not locally.
> Testing: disable check for 'green' status

- client-python/elastiknn/client.py
- taskfiles/Taskfile.annb.yaml
- #387 
Ensures that the ann-benchmarks tests are actually running the elastiknn algos. 
Prior to this, elastiknn was _not_ running, as the dataset was set to an angular dataset, and the elastiknn models are only setup for euclidean.
CI
> #387: Fix ann-benchmarks tests

- ann-benchmarks/README.md
- build.gradle
- taskfiles/Taskfile.annb.yaml
- #387 
- Remove unused variable from build.gradle
- Fix ann-benchmarks dataset name in Taskfile.annb.yaml
- Use `task cluster:start` more consistently in ann-benchmarks/README.md 
Standard CI
> #387: Minor benchmarking fixes

- .github/workflows/ci.yml
- .github/workflows/release.yml
- Resolves #400 
Added timeouts on workflow jobs. The original issue seemed to resolve itself. This will just make sure the job doesn't hang indefinitely if it happens again. 
Standard CI
> #400: Set timeouts on github workflow jobs

- .github/scripts/setup-env.sh
- .github/workflows/ci.yml
- .github/workflows/release.yml
- README.md
- build.gradle
- docs/pages/libraries.md
- taskfiles/Taskfile.jvm.yaml
- Resolves #392 
Removed publish configuration and automation for all JVM libraries: com.klibisz.elastiknn:models, com.klibisz.elastiknn:lucene, com.klibisz.elastiknn:client-elastic4s_2.13, com.klibisz.elastiknn:api4s_2.13 
Standard CI
> #392: Stop publishing JVM libraries

- .github/workflows/ci.yml
- .github/workflows/release.yml
Noticed that some builds are failing to resolve dependencies from bintray:
- https://github.com/alexklibisz/elastiknn/actions/runs/3085494976/jobs/4988848293
- https://github.com/alexklibisz/elastiknn/actions/runs/3085494979/jobs/4988847979
- Upgrade setup-java Github action from v1 to v3
- Add Gradle caching
How was it validated?
- Standard CI
> Build: Upgrade setup-java action and add Gradle caching

- .github/workflows/ci.yml
- .github/workflows/release.yml
- #360 
- Re-build the cache for every commit by keying on the commit name instead of the branch name. The previous strategy used the branch name in the key. But, if an entry already exists in the cache, it won't be overridden. Github will just continue pulling the older entry. That means it keeps pulling the 7-day old master-branch entry when running for a push to master, and keeps pulling the first entry from a given branch when running for a PR. To solve this, we can key on the commit sha, with a fallback to the previous commit sha. This will create more churn in the cache, but it doesn't really matter since Github cleans all of that up.
How was it validated?
> Build: re-build the cache for every commit

- .github/workflows/ci.yml
- .sbtopts
- build.sbt
- elastiknn-testing/docker-compose.yml
- elastiknn-testing/src/test/scala/com/klibisz/elastiknn/query/RecallSuite.scala
- #400 
- Remove DoNotDiscover from RecallSuite
- Explicit limits on memory for the docker containers.
- Standard CI
> Build: reinstate RecallSuite

- .github/workflows/ci.yml
- .github/workflows/release.yml
#420 
Cache on the run number instead of the sha. Based on trick from here: https://github.com/actions/cache/issues/2#issuecomment-1259332802
Standard CI
> Build: cache on run_number

- .github/workflows/release.yml
- #442 
Add workflow_dispatch to on section in release.yaml to make the workflow runnable from the actions tab.
See if it works in actions tab
> Build: make the release workflow runnable from Actions tab

- .github/workflows/release.yml
- #442 
Set token permissions to address this error:
Re-run after merging
> Build: fix permissions on Github token

- .github/workflows/release.yml
- docs/pages/libraries.md
- taskfiles/Taskfile.python.yaml
- #442 
- Fix some text in the libraries page
- Publish the python docs to github pages
- Will run release post-merge
> Build: Publish Python docs to Github pages

- .github/workflows/release.yml
- #442 
Ubuntu 22 doesn't seem to support python 3.7.5. Probably best to update to newer ubuntu as a separate task.
Also no longer need the "Publish Python Docs" step in the main release.
Merge-and-check
> Build: Use ubuntu-20.04 to generate docs and remove Publish Python Docs step

- .github/workflows/ci.yml
- .github/workflows/release.yml
- Taskfile.yaml
- docker/cluster_ready.py
None
- Upgrade all workflows except test-benchmarks to run on ubuntu-22.04.
- Use the setup-task action instead of `snap` to install the task CLI.
- Improve some of the step names
Standard CI
> Build: upgrade workflows from ubuntu-20.04 to ubuntu-22.04 where possible

- .github/workflows/release.yml
None
- Only run the release workflow on manual dispatch, not automatically
- Upgrade the release to use setup-python@v4
Standard CI
> Build: only release on workflow_dispatch

- .gitignore
#493
Pointing the submodule at the ann-benchmarks master branch after the Elastiknn upgrade PR was merged.
Standard CI
> Benchmarks: point submodule at ann-benchmarks master

- docs/_config.yml
Fixing the url and baseurl to account for having a path in the URL now.
> Docs: fix Jekyll url and baseurl

- Taskfile.yaml
- developer-guide.md
- docker/docker-compose.testing.yaml
Tangentially related to #525
Using `docker compose` command instead of `docker-compose`
Standard Ci
> Build: use docker compose instead of docker-compose

- .github/scripts/setup-env.sh
- .github/workflows/ci.yaml
- .github/workflows/pypirc.template
- .github/workflows/release.yml
#561
Switching from password-based auth to token-based auth on test.pypi.org and pypi.org. I created tokens on test.pypi.org and pypi.org, set them as repo secrets, and modified the release jobs so that they substitute the tokens into the ~/.pypirc file.
This worked locally:
```bash
➜  elastiknn git:(fix-pypi) envsubst < .github/workflows/pypirc.template > ~/.pypirc   
➜  elastiknn git:(fix-pypi) task pyPublishSnapshot                                  
task: Task "pyCreateVenv" is up to date
task: [pyInstallRequirements] venv/bin/pip install --quiet -r requirements.txt
[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: /Users/alex/Development/repos/elastiknn/client-python/venv/bin/python -m pip install --upgrade pip
task: [pyInstallRequirements] …
```
> Build: use token for pypi releases

- .github/workflows/release.yml
Same as #563, except this time I'm including the actual change.
> Build: fix python version in release workflow

- .github/workflows/scala-steward.yaml
None
Running scala-steward once/month instead of once/week. Don't have time to review the PRs weekly, and the benefit is negligible.
Set it to the sixth, so we'll see if it runs tonight.
> Build: run scala-steward once/month

- .github/workflows/release.yml
None
Modifying the release workflow so that I can run a snapshot release from main.
Ran the release workflow on this branch.
> Build: allow snapshot release from main

- client-python/requirements.txt
None
Dataclasses are part of the language in newer versions of Python. At this point we shouldn't need the dependency anymore.
Standard CI
> client-python: remove dependency on dataclasses

- docker/docker-compose.testing.yaml
N/A
Increasing memory in the testing master service because it was OOMing locally.
Standard CI
> Build: increase testing memory

- docs/_posts/2020-12-15-elastic-meetup-presentation-demo-december-2020.md
- docs/_posts/2021-07-30-how-does-elastiknn-work.md
N/A
The images on the posts are broken. I guess this happened when I changed the site URL, #442 
Will merge, release docs, and verify they're fixed
> Docs: fix image URLs

- elastiknn-lucene/src/main/java/com/klibisz/elastiknn/search/EmptyHitCounter.java
- elastiknn-lucene/src/main/java/org/apache/lucene/search/MatchHashesAndScoreQuery.java
None
Added an EmptyHitCounter for cases where `reader.terms` returns null. Just an improvement for aesthetics and code clarity, no actual impact on performance.
Standard CI
> Refactor: Add EmptyHitCounter for use in MatchHashesAndScoreQuerySuite

- docker/docker-compose.benchmarking.yaml
#611 
Adding JVM flags to support attaching VisualVM to the benchmarking docker container
Tested localy
> Build: add visualvm flags to benchmarking docker-compose setup

- elastiknn-models/src/test/scala/com/klibisz/elastiknn/vectors/PanamaFloatVectorOpsSpec.scala
Maybe #617 
Some tests have been failing recently with errors like: 
https://github.com/alexklibisz/elastiknn/actions/runs/7152449485/job/19477803203?pr=630
The implementation seems fine. E.g., the RecallSuite continues to pass with no meaningful changes and the benchmarks, too. So I'm just bumping up the error tolerance here.
Standard CI
> Tests: increase error tolerance in PanamaFloatVectorOpsSpec

- project/ElasticsearchPluginPlugin.scala
> Build: fix the Elasticsearch download URL so it works on Linux

- elastiknn-api4s/src/main/scala/com/klibisz/elastiknn/api/Vec.scala
fix java.security.AccessControlException caused by ClassTag from DenseFloat.toString
Link the related issues as a markdown list.
- #785
- #393
- #656
the call values.take(3).map(n => f"$n%.2f")   will trigger scala.reflect.ClassTag
so change the call chain to  values.take(3).iterator.map(n => f"$n%.2f") ，which can avoid calling this scala.reflect.ClassTag
```
curl -H'Content-Type: application/json' -X GET http://localhost:9200/my-vector-index4/_search -d'{
"query": {
"elastiknn_nearest_neighbors": {
"field": "my_vec1",
"vec": {
"values": [1,1,1,1,1,1,1,1,1,1]
},
"model": "lsh",
"similarity": "jaccard",
"candidates": 50
}
}
}'
{"error":{"root_cause":[{"type":"query_shard_exception","reason":"failed to create query: Query [JaccardLsh(my_vec1,50,DenseFloat(1.00,1.00,1.00,...,10))] is not …
```
> #785: fix java.security.AccessControlException caused by ClassTag 
